In [1]:
######################################################################
# Description ########################################################
######################################################################
'''
Python code for meta reinforcement learning
For a single simulation,
  sim=Sim()
  sim.run()
For batch simulations,
  batch=Batch()
  batch.run()
'''


######################################################################
# Parameters #########################################################
######################################################################

set_param_sim='param_sim.json'
#set_param_sim='param_sim_long.json'
#set_param_sim='param_test.json'
#set_param_sim='param_test_load.json'

set_param_mod='param_wang2018.json'
#set_param_mod='param_wang2018_parallel.json'

#dir_restart='20200219_223846'
#dir_restart='20200221_234851'
#dir_restart='20200222_002120'
dir_restart=None

dir_load='20200222_002120/20200222_122717'
#dir_load=None

param_batch=[
    #{'name': 'learning_rate', 'n':11, 'type':'parametric','method':'grid','min':0.0002,'max':0.0052}
    #{'name': 'learning_rate', 'n':10, 'type':'parametric','method':'grid','min':0.0057,'max':0.0102},
    #{'name': 'learning_rate', 'n':100, 'type':'parametric','method':'grid','min':0.0001,'max':0.0100},
    #{'name': 'learning_rate', 'n':2, 'type':'parametric','method':'grid','min':0.0001,'max':0.0100},
    #{'name':'dummy_counter', 'n':3, 'type':'parametric', 'method':'grid', 'min':0,'max':2}
    #{'name':'learning_rate', 'n':5, 'type':'parametric', 'method':'random', 'min':0.0001, 'max':0.001},
    #{'name':'optimizer', 'n':2, 'type':'list','list':['RMSProp','Adam']}
    #{'name':'gamma','n':3,'type':'parametric','method':'grid','min':0.7,'max':0.9}
    #{'name': 'n_cells_lstm', 'n':20, 'type':'parametric','method':'grid','min':5,'max':100}
    {'name': 'learning_rate', 'n':19, 'type':'parametric','method':'grid','min':0.0001,'max':0.0019},
    #{'name': 'learning_rate', 'n':17, 'type':'parametric','method':'grid','min':0.002,'max':0.01}
    #{'name': 'episode_stop', 'n':5, 'type':'parametric','method':'grid','min':50000,'max':0.01}
]


######################################################################
# Libraries ##########################################################
######################################################################

import os
list_path_code=[
    'D:/atiroms/GitHub/Schizophrenia_Model/Model_03',
    'C:/Users/atiro/GitHub/Schizophrenia_Model/Model_03',
    '/home/atiroms/GitHub/Schizophrenia_Model/Model_03'
]
for i in range(len(list_path_code)):
    if os.path.exists(list_path_code[i]):
        path_code=list_path_code[i]
        os.chdir(path_code)
        break
    elif i==len(list_path_code)-1:
        raise ValueError('Code folder does not exist in the list.')
list_path_save=[
    "/media/veracrypt1/Machine_Learning/Schizophrenia_Model/saved_data",
    "/media/atiroms/MORITA_HDD3/Machine_Learning/Schizophrenia_Model/saved_data",
    "C:/Users/atiro/Documents/Machine_Learning/Schizophrenia_Model/saved_data",
    "D:/Machine_Learning/Schizophrenia_Model/saved_data",
    "F:/Machine_Learning/Schizophrenia_Model/saved_data"
]
for i in range(len(list_path_save)):
    if os.path.exists(list_path_save[i]):
        path_save=list_path_save[i]
        break
    elif i==len(list_path_save)-1:
        raise ValueError('Save folder does not exist in the list.')

import threading
#import multiprocessing
import numpy as np
#import matplotlib.pyplot as plt
import tensorflow as tf
import datetime
import time
import pandas as pd
import json
import Agent
import Network
import Environment


######################################################################
# Parameters class for parameter exchange between classes ############
######################################################################

class Parameters():
    def __init__(self,set_param,path_code=path_code):
        self.set=None
        self.add_json(set_param,path_code)

    def add_dict(self,dict_param):
        for key,value in dict_param.items():
            if key!="//":
                setattr(self,key,value)

    def add_json(self,set_param,path_code=path_code):
        with open(os.path.join(path_code,"parameters",set_param)) as f:
            dict_param=json.load(f)
            self.add_dict(dict_param)
        if self.set is None:
            self.set=list()
        self.set.append(set_param)


######################################################################
# Single run of simulation ###########################################
######################################################################

class Sim():
    #def __init__(self,param_basic=param_basic,param_change=None):
    def __init__(self,set_param_sim=set_param_sim,set_param_mod=set_param_mod,
                 set_param_overwrite=None,
                 path_code=path_code,path_save=path_save,
                 path_save_batch=None,
                 dir_load=dir_load):

        # Timestamping directory name
        datetime_start="{0:%Y%m%d_%H%M%S}".format(datetime.datetime.now())
        if path_save_batch is not None:
            path_save_run=os.path.join(path_save_batch,datetime_start)
        else:
            path_save_run=os.path.join(path_save,datetime_start)
        self.path_save=path_save

        # Setup parameters in Parmeters object
        self.param=Parameters(set_param_sim,path_code)
        self.param.add_json(set_param_mod,path_code)
        self.param.add_dict({'datetime_start':datetime_start, 'path_save':path_save_run})
        if set_param_overwrite is not None:
            self.param.add_dict(set_param_overwrite)
        if dir_load is not None:
            with open(os.path.join(path_save,dir_load,"parameters.json")) as f:
                dict_param=json.load(f)
            episode_done=dict_param['episode_stop']
            episode_stop=episode_done+self.param.episode_stop
            print('episode_stop='+str(episode_done)+'+'+str(self.param.episode_stop))
            self.param.add_dict({'load_model':1,'dir_load':dir_load,'episode_stop':episode_stop})
        else:
            self.param.add_dict({'load_model':0})


        # Make directories for saving
        if not os.path.exists(self.param.path_save):
            os.makedirs(self.param.path_save)
        for subdir in ['model','pic','summary','activity']:
            if not os.path.exists(os.path.join(self.param.path_save,subdir)):
                os.makedirs(os.path.join(self.param.path_save,subdir))
        
        # Save parameters
        with open(os.path.join(self.param.path_save,'parameters.json'), 'w') as fp:
            json.dump(self.param.__dict__, fp, indent=1)

    def run(self):
        print('Running: '+ self.param.datetime_start + '.')
        tf.reset_default_graph()
        # Setup agents for multiple threading
        with tf.device(self.param.xpu):
            # counter of total episodes defined outside A2C_Agent class
            self.episode_global = tf.Variable(0,dtype=tf.int32,name='episode_global',trainable=False)
            if self.param.optimizer == "Adam":
                self.trainer = tf.train.AdamOptimizer(learning_rate=self.param.learning_rate)
            elif self.param.optimizer == "RMSProp":
                self.trainer = tf.train.RMSPropOptimizer(learning_rate=self.param.learning_rate)
            if self.param.environment == 'Two_Armed_Bandit':
                env_alias=Environment.Two_Armed_Bandit
            elif self.param.environment == 'Dual_Assignment_with_Hold':
                env_alias=Environment.Dual_Assignment_with_Hold
            # Generate master network
            self.master_network = Network.LSTM_RNN_Network(self.param,
                                                           env_alias(self.param.config_environment).n_actions,
                                                           'master',None) 
            #n_agents = multiprocessing.cpu_count() # Set agents to number of available CPU threads
            self.saver = tf.train.Saver(max_to_keep=5)
            self.agents = []
            # Create A2C_Agent classes (local network is defined within agent definition)
            for i in range(self.param.n_agents):
                self.agents.append(Agent.A2C_Agent(i,self.param,env_alias(self.param.config_environment),
                                                   self.trainer,self.saver,self.episode_global))

        # Run agents
        #config=tf.ConfigProto(allow_soft_placement=True, log_device_placement=True)
        config=tf.ConfigProto(allow_soft_placement=True)
        with tf.Session(config=config) as sess:
            sess.run(tf.global_variables_initializer())
            if self.param.load_model == True:
                #ckpt = tf.train.get_checkpoint_state(self.param.path_load+'/model')
                path_load=os.path.join(self.path_save,self.param.dir_load)
                ckpt = tf.train.get_checkpoint_state(os.path.join(path_load,'model'))
                self.saver.restore(sess,ckpt.model_checkpoint_path)
                print('Loaded parameters: '+ self.param.dir_load + '.')
            #else:
                #sess.run(tf.global_variables_initializer())
            coord = tf.train.Coordinator()
            #if self.param.xpu=='/gpu:0' and self.param.n_agents==1:
            if self.param.n_agents==1:
                self.agents[0].work(sess,coord)
            elif self.param.xpu=='/gpu:0' and self.param.n_agents>1:
                raise ValueError('Multi-threading not allowed with GPU.')
            else:
                agent_threads = []
                for agent in self.agents:
                    agent_work = lambda: agent.work(sess,coord)
                    thread = threading.Thread(target=(agent_work))
                    thread.start()
                    agent_threads.append(thread)
                coord.join(agent_threads)
        print('Done single run: '+ self.param.datetime_start + '.')


######################################################################
# Batch run of simulations ###########################################
######################################################################

class Batch():
    def __init__(self,param_batch=param_batch,path_save=path_save,
                 dir_restart=dir_restart):
        if dir_restart is None:
            self.prep(param_batch=param_batch,path_save=path_save)
        else:
            self.prep_restart(dir_restart=dir_restart,path_save=path_save)

    def prep_restart(self,dir_restart,path_save):
        self.path_save_batch=os.path.join(path_save,dir_restart)
        if os.path.exists(os.path.join(self.path_save_batch,"batch_table.h5")):
            with pd.HDFStore(os.path.join(self.path_save_batch,"batch_table.h5")) as hdf:
                self.batch_table = pd.DataFrame(hdf['batch_table'])
            self.batch_table.loc[:,'run']=False
            list_idx_rerun=self.batch_table.loc[self.batch_table['done']==False,:].index.values.tolist()
            print('Unfinished runs: '+str(len(list_idx_rerun))+'.')
            for i in list_idx_rerun:
                sr_append=self.batch_table.loc[i,:]
                sr_append['datetime_start']=np.NaN
                sr_append['run']=True
                sr_append['done']=False
                self.batch_table=self.batch_table.append(sr_append)
            self.batch_table=self.batch_table.reset_index(drop=True)
            self.save_batch_table()
            print('Done batch setup for restart.')
        else:
            print('dir_restart not found: '+dir_restart)

    def prep(self,param_batch=param_batch,path_save=path_save):
        self.n_param=len(param_batch)
        # Timestamping directory name
        datetime_start="{0:%Y%m%d_%H%M%S}".format(datetime.datetime.now())
        self.path_save_batch=os.path.join(path_save,datetime_start)
        if not os.path.exists(self.path_save_batch):
            os.makedirs(self.path_save_batch)

        # Batch table preparation
        batch_current_id=np.zeros((self.n_param,),dtype=np.int16) # table of ids of iteration for each parameter
        self.batch_table=pd.DataFrame()
        batch_count=0
        flag_break=0        # 1: batch current id update successfull, 2: end of recursion
        while flag_break < 2:
            for i in range(self.n_param):
                param=param_batch[i]
                if param['type']=='list':
                    self.batch_table.loc[batch_count,param['name']] = param['list'][batch_current_id[i]]
                elif param['type']=='parametric':
                    if param['method']=='grid':
                        self.batch_table.loc[batch_count,param['name']] = param['min']+(param['max']-param['min'])*batch_current_id[i]/(param['n']-1)
                    elif param['method']=='random':
                        self.batch_table.loc[batch_count,param['name']] = np.random.uniform(low=param['min'],high=param['max'])
                else:
                    raise ValueError('Incorrect batch parameter type.')

            param_id_level=self.n_param-1
            flag_break=0
            while flag_break < 1:
                batch_current_id[param_id_level] += 1
                if batch_current_id[param_id_level] < param_batch[param_id_level]['n']:
                    # break updating id when within limit
                    flag_break = 1
                else:
                    # reset current level to 0
                    batch_current_id[param_id_level] = 0
                    # move to the upper level
                    param_id_level -= 1
                    if param_id_level < 0:
                        # break creating list when reached end
                        flag_break = 2

            batch_count += 1

        self.batch_table.loc[:,'datetime_start']=np.NaN
        self.batch_table.loc[:,'run']=True
        self.batch_table.loc[:,'done']=False
        self.save_batch_table()

        with open(self.path_save_batch+'/parameters_batch.json', 'w') as fp:
            json.dump(param_batch, fp, indent=1)

        print('Done batch setup.')

    def run(self):
        batch_table_run=self.batch_table.loc[self.batch_table['run']==True,:]
        #for i in range(len(self.batch_table)):
        list_idx_run=batch_table_run.index.values.tolist()
        for i in range(len(list_idx_run)):
            idx=list_idx_run[i]
            print('Batch simulation: ' + str(i + 1) + '/' + str(len(list_idx_run)),'.')
            param_overwrite=self.batch_table.loc[idx,self.batch_table.columns.difference(['datetime_start','run','done'])].to_dict()
            param_overwrite['path_save_batch']=self.path_save_batch
            sim=Sim(path_save_batch=self.path_save_batch,set_param_overwrite=param_overwrite)
            self.batch_table.loc[idx,'datetime_start']=sim.param.datetime_start
            self.save_batch_table()
            sim.run()
            self.batch_table.loc[idx,'done']=True
            self.save_batch_table()
        print('Done batch simulation.')

    def save_batch_table(self):
        hdf=pd.HDFStore(self.path_save_batch+'/batch_table.h5')
        hdf.put('batch_table',self.batch_table,format='table',append=False,data_columns=True)
        hdf.close()

print('End of file.')

End of file.


In [186]:
sim=Sim()

sim.param.n_cells_lstm=50

tf.reset_default_graph()
with tf.device(sim.param.xpu):
    
    env_alias=Environment.Two_Armed_Bandit

    sim.episode_global = tf.Variable(0,dtype=tf.int32,name='episode_global',trainable=False)

    sim.master_network = Network.LSTM_RNN_Network(sim.param,
                                                  env_alias(sim.param.config_environment).n_actions,
                                                  'master',None) 
            
    sim.saver = tf.train.Saver(max_to_keep=5)
    sim.trainer = tf.train.RMSPropOptimizer(learning_rate=sim.param.learning_rate)

    sim.agents = []
    sim.agents.append(Agent.A2C_Agent(0,sim.param,env_alias(sim.param.config_environment),sim.trainer,sim.saver,sim.episode_global))

episode_stop=200000+50000


In [87]:
path_parameter=os.path.join(path_save,'20200222_002120/20200222_122717/parameters.json')
with open(path_parameter) as f:
    dict_param=json.load(f)
n_cells=dict_param['n_cells_lstm']
n_actions=env_alias(sim.param.config_environment).n_actions

In [88]:
path_variable=os.path.join(path_save,'20200222_002120/20200222_122717/model/variable.h5')
with pd.HDFStore(path_variable) as hdf:
    df_var = pd.DataFrame(hdf['variable'])
df_var=df_var.loc[df_var['episode']==max(df_var['episode']),:]
len(df_var)

10320

In [220]:
ary_var=np.asarray(df_var['value'],order='c').astype('float32')
ary_kernel,ary_bias,ary_fc0,ary_fc1=np.split(ary_var,
                                             [(n_actions+2+n_cells)*4*n_cells,
                                              (n_actions+3+n_cells)*4*n_cells,
                                              ((n_actions+3+n_cells)*4+n_actions)*n_cells])
ary_kernel=ary_kernel.reshape([4+n_cell,4*n_cell])
ary_bias=ary_bias.reshape([4*n_cell])
ary_fc0=ary_fc0.reshape([n_cell,2])
ary_fc1=ary_fc1.reshape([n_cell])

In [224]:
sess=tf.Session()
sess.run(tf.global_variables_initializer())
vars_master = tf.get_collection(tf.GraphKeys.TRAINABLE_VARIABLES,'master')
#vars_agent0 = tf.get_collection(tf.GraphKeys.TRAINABLE_VARIABLES,'agent_0')
val_initialized = sess.run(vars_master)
ary_kernel_init,ary_bias_init,ary_fc0_init,ary_fc1_init=val_initialized

In [229]:
n_cells_new=sim.param.n_cells_lstm
#n_cells_new=50
if n_cells_new<n_cells:
    idx_del=np.arange(n_cells_new,n_cells)
    idx_del_4=[]
    for i in range(4):
        idx_del_4=np.concatenate([idx_del_4,idx_del+n_cells*i])
    
    ary_kernel=np.delete(ary_kernel,idx_del+n_actions+2,0)
    ary_kernel=np.delete(ary_kernel,idx_del_4,1)
    ary_bias=np.delete(ary_bias,idx_del_4,0)
    ary_fc0=np.delete(ary_fc0,idx_del,0)
    ary_fc1=np.delete(ary_fc1,idx_del,0)
elif n_cells_new>n_cells:
    idx_ow=np.arange(n_cells)
    idx_ow_4=[]
    for i in range(4):
        idx_ow_4=np.concatenate([idx_ow_4,idx_ow+n_cells_new*i])
    idx_ow_4=idx_ow_4.astype('int64')
    ary_kernel_init[np.concatenate([np.arange(n_actions+2),idx_ow+n_actions+2]),:][:,idx_ow_4]=ary_kernel

In [228]:
ary_kernel_init[np.concatenate([np.arange(n_actions+2),idx_ow+n_actions+2]),:][:,idx_ow_4].shape

(52, 192)

In [232]:
ary_kernel

array([[ 0.17478107,  0.36658743,  0.13955773, ..., -0.30500987,
        -0.8377609 ,  1.4047496 ],
       [ 1.8260309 , -0.14977968,  3.3351798 , ..., -0.05376303,
        -0.3583426 , -0.2581303 ],
       [ 0.12995254,  0.29092982,  0.25013828, ...,  0.1417551 ,
        -0.0931776 ,  0.17620383],
       ...,
       [ 0.16412885,  0.18688573,  0.25903976, ..., -0.23034962,
        -0.20982312, -0.3965033 ],
       [-0.08965965, -0.17973563, -0.19185443, ...,  0.1911813 ,
        -0.56123155,  0.45094624],
       [ 0.39427224,  0.34855536,  0.22236167, ..., -0.25119653,
        -0.1319986 ,  0.1018885 ]], dtype=float32)

In [231]:
ary_kernel_init

array([[ 0.08465214,  0.08134119,  0.13187745, ...,  0.0044484 ,
         0.09659958,  0.00904743],
       [ 0.06097649, -0.06721371, -0.14511333, ...,  0.00502205,
        -0.11208597, -0.08963274],
       [-0.09176691,  0.13899899, -0.00884718, ...,  0.13978851,
        -0.15157728, -0.02917983],
       ...,
       [-0.01647455, -0.04324282,  0.01957431, ..., -0.09864902,
         0.03227679, -0.03520437],
       [-0.13885826, -0.07119974,  0.02865747, ..., -0.04150796,
        -0.08949558, -0.01221052],
       [ 0.10034782,  0.10746241, -0.11666793, ...,  0.02765666,
        -0.05073564, -0.12761536]], dtype=float32)

In [237]:
ary_test=np.arange(12).reshape([3,4])

In [241]:
ary_test[[0,1],:][:,[0,1,2]]=np.arange(6,12).reshape([2,3])

In [242]:
ary_test

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [243]:
np.arange(6,12).reshape([2,3])

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [45]:
sess.run(vars_master[0].assign(array_kernel))
val_loaded = sess.run(vars_master)
val_loaded[0]

array([[ 0.17478107,  0.36658743,  0.13955773, ..., -0.30500987,
        -0.8377609 ,  1.4047496 ],
       [ 1.8260309 , -0.14977968,  3.3351798 , ..., -0.05376303,
        -0.3583426 , -0.2581303 ],
       [ 0.12995254,  0.29092982,  0.25013828, ...,  0.1417551 ,
        -0.0931776 ,  0.17620383],
       ...,
       [ 0.16412885,  0.18688573,  0.25903976, ..., -0.23034962,
        -0.20982312, -0.3965033 ],
       [-0.08965965, -0.17973563, -0.19185443, ...,  0.1911813 ,
        -0.56123155,  0.45094624],
       [ 0.39427224,  0.34855536,  0.22236167, ..., -0.25119653,
        -0.1319986 ,  0.1018885 ]], dtype=float32)

In [20]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    #vars_agent0 = tf.get_collection(tf.GraphKeys.TRAINABLE_VARIABLES,'agent_0')
    val_initialized = sess.run(vars_master)

In [7]:
vars_master = tf.get_collection(tf.GraphKeys.TRAINABLE_VARIABLES,'master')
tf.reset_default_graph()
config=tf.ConfigProto(allow_soft_placement=True)
with tf.Session(config=config) as sess:
    #sess.run(tf.global_variables_initializer())
    path_load=os.path.join(path_save,'20200222_002120/20200222_122717')
    ckpt = tf.train.get_checkpoint_state(os.path.join(path_load,'model'))
    saver=tf.train.Saver(max_to_keep=5)
    saver.restore(sess,ckpt.model_checkpoint_path)
    val_loaded=sess.run(vars_master)

ValueError: No variables to save

In [18]:
val_initialized[0].shape

(9, 20)

In [13]:
val_loaded[0]

array([[ 0.17478107,  0.36658743,  0.13955773, ..., -0.30500987,
        -0.8377609 ,  1.4047496 ],
       [ 1.8260309 , -0.14977968,  3.3351798 , ..., -0.05376303,
        -0.3583426 , -0.2581303 ],
       [ 0.12995254,  0.29092982,  0.25013828, ...,  0.1417551 ,
        -0.0931776 ,  0.17620383],
       ...,
       [ 0.16412885,  0.18688573,  0.25903976, ..., -0.23034962,
        -0.20982312, -0.3965033 ],
       [-0.08965965, -0.17973563, -0.19185443, ...,  0.1911813 ,
        -0.56123155,  0.45094624],
       [ 0.39427224,  0.34855536,  0.22236167, ..., -0.25119653,
        -0.1319986 ,  0.1018885 ]], dtype=float32)

In [8]:
vars_master

[<tf.Variable 'master/rnn/LSTM_Cells/kernel:0' shape=(52, 192) dtype=float32_ref>,
 <tf.Variable 'master/rnn/LSTM_Cells/bias:0' shape=(192,) dtype=float32_ref>,
 <tf.Variable 'master/fully_connected/weights:0' shape=(48, 2) dtype=float32_ref>,
 <tf.Variable 'master/fully_connected_1/weights:0' shape=(48, 1) dtype=float32_ref>]

In [17]:
#sess.run(tf.global_variables_initializer())
path_load=os.path.join(sim.path_save,sim.param.dir_load)
ckpt = tf.train.get_checkpoint_state(os.path.join(path_load,'model'))
sim.saver.restore(sess,ckpt.model_checkpoint_path)
sess.run(vars_master)